name: Publish to NPM

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Check for script changes
        id: changes
        run: |
          # Get the last published tag, or use initial commit if no tags exist
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || git rev-list --max-parents=0 HEAD)
          echo "Comparing changes since: $LAST_TAG"
          
          # Check if index.js, src/, or package.json (excluding version field) changed since last published version
          if git diff $LAST_TAG...HEAD --name-only | grep -E '^(index\.js|src/|package\.json)$' | grep -v -E '\.(md|test\.js|spec\.js)$'; then
            # If package.json changed, check if it's not just the version field
            if git diff $LAST_TAG...HEAD --name-only | grep -q package.json; then
              # Check if changes are more than just version
              if git diff $LAST_TAG...HEAD package.json | grep -v '"version"' | grep -E '^[+-]' | grep -v -E '^[+-]{3}|^@@'; then
                echo "script-changed=true" >> $GITHUB_OUTPUT
                echo "core-changed=true" >> $GITHUB_OUTPUT
              elif git diff $LAST_TAG...HEAD --name-only | grep -E '^(index\.js|src/)'; then
                echo "script-changed=true" >> $GITHUB_OUTPUT
                echo "core-changed=true" >> $GITHUB_OUTPUT
              else
                echo "script-changed=false" >> $GITHUB_OUTPUT
                echo "core-changed=false" >> $GITHUB_OUTPUT
              fi
            else
              echo "script-changed=true" >> $GITHUB_OUTPUT
              echo "core-changed=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "script-changed=false" >> $GITHUB_OUTPUT
            echo "core-changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Configure git
        if: steps.changes.outputs.script-changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Build web bundle
        if: steps.changes.outputs.core-changed == 'true'
        run: |
          # Create web-compatible bundle from core module
          cp src/core-web.js src/core-bundle.js
          
      - name: Bump version and publish
        if: steps.changes.outputs.script-changed == 'true'
        run: |
          npm version patch
          git push origin master --tags
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Trigger Homebrew formula update
        if: steps.changes.outputs.script-changed == 'true'
        run: |
          # Get the new version from package.json
          NEW_VERSION=$(node -p "require('./package.json').version")
          
          # Trigger the homebrew repository to update
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.HOMEBREW_DISPATCH_TOKEN }}" \
            https://api.github.com/repos/gift-calc/homebrew-gift-calc/dispatches \
            -d "{\"event_type\":\"version_update\",\"client_payload\":{\"version\":\"$NEW_VERSION\"}}"
          
      - name: Sync core to website
        if: steps.changes.outputs.core-changed == 'true'
        run: |
          # Clone the website repository
          git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/gift-calc/gift-calc.github.io.git website-repo
          
          # Create js directory if it doesn't exist
          mkdir -p website-repo/js
          
          # Copy the web-compatible core
          cp src/core-web.js website-repo/js/core.js
          
          # Configure git for website repo
          cd website-repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Commit and push if there are changes
          if ! git diff --quiet js/core.js; then
            git add js/core.js
            git commit -m "Update core calculation logic from main repository"
            git push origin master
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}